/**
 * YOUR_HOME_SMALL_CLASS_APP_ID :小班课 - 国内环境
 * YOUR_OVERSEAS_SMALL_CLASS_APP_ID: 小班课- 海外环境
 * YOUR_HOME_LARGE_CLASS_APP_ID: 大班课 - 国内环境
 * YOUR_OVERSEAS_LARGE_CLASS_APP_ID: 大班课 - 海外环境
 * YOUR_HOME_SMALL_CLASS_SEVERURL: 国内小班课appID 对应 server地址
 * YOUR_OVERSEAS_SMALL_CLASS_SEVERURL: 海外小班课appID 对应 server地址
 * YOUR_HOME_LARGE_CLASS_SEVERURL: 国内大班课appID 对应 server地址
 * YOUR_OVERSEAS_LARGE_CLASS_SEVERURL: 海外大班课appID 对应 server地址
 * YOUR_HOME_BACKEND_URL: 后台业务正式环境-国内环境
 * YOUR_OVERSEAS_BACKEND_URL: 后台业务正式环境-海外环境
 * YOUR_SDK_TOKEN_URL: 获取 token URL
 * SERVER_IS_TEST_ENV: 为环境标识，可通过此字段切换为测试环境
 * DOCS_IS_TEST_ENV:为环境标识，可通过此字段切换文件转码为测试环境
 */
 const YOUR_HOME_SMALL_CLASS_APP_ID = 0
 const YOUR_OVERSEAS_SMALL_CLASS_APP_ID = 0
 const YOUR_HOME_LARGE_CLASS_APP_ID = 0
 const YOUR_OVERSEAS_LARGE_CLASS_APP_ID = 0
 
 const YOUR_HOME_SMALL_CLASS_SEVERURL = ''
 const YOUR_OVERSEAS_SMALL_CLASS_SEVERURL = ''
 
 const YOUR_HOME_LARGE_CLASS_SEVERURL = ''
 const YOUR_OVERSEAS_LARGE_CLASS_SEVERURL = ''
 
 const YOUR_HOME_BACKEND_URL = ''
 const YOUR_OVERSEAS_BACKEND_URL = ''
 
 const YOUR_SDK_TOKEN_URL = ''
 const SERVER_IS_TEST_ENV = false
 const DOCS_IS_TEST_ENV = true
 
 export {
   YOUR_HOME_SMALL_CLASS_APP_ID,
   YOUR_OVERSEAS_SMALL_CLASS_APP_ID,
   YOUR_HOME_LARGE_CLASS_APP_ID,
   YOUR_OVERSEAS_LARGE_CLASS_APP_ID,
   YOUR_HOME_SMALL_CLASS_SEVERURL,
   YOUR_OVERSEAS_SMALL_CLASS_SEVERURL,
   YOUR_HOME_LARGE_CLASS_SEVERURL,
   YOUR_OVERSEAS_LARGE_CLASS_SEVERURL,
   YOUR_HOME_BACKEND_URL,
   YOUR_OVERSEAS_BACKEND_URL,
   YOUR_SDK_TOKEN_URL,
   SERVER_IS_TEST_ENV,
   DOCS_IS_TEST_ENV
 }