/**
 * YOUR_HOME_SMALL_CLASS_APP_ID :小班课 - 国内环境
 * YOUR_OVERSEAS_SMALL_CLASS_APP_ID: 小班课- 海外环境
 * YOUR_HOME_LARGE_CLASS_APP_ID: 大班课 - 国内环境
 * YOUR_OVERSEAS_LARGE_CLASS_APP_ID: 大班课 - 海外环境
 * YOUR_HOME_BACKEND_URL: 后台业务正式环境-国内环境
 * YOUR_OVERSEAS_BACKEND_URL: 后台业务正式环境-海外环境
 * YOUR_SDK_TOKEN_URL: 获取 token URL
 */
const YOUR_HOME_SMALL_CLASS_APP_ID = 0
const YOUR_OVERSEAS_SMALL_CLASS_APP_ID = 0
const YOUR_HOME_LARGE_CLASS_APP_ID = 0
const YOUR_OVERSEAS_LARGE_CLASS_APP_ID = 0
const YOUR_HOME_BACKEND_URL = ''
const YOUR_OVERSEAS_BACKEND_URL = ''
const YOUR_SDK_TOKEN_URL = ''

export {
  YOUR_HOME_SMALL_CLASS_APP_ID,
  YOUR_OVERSEAS_SMALL_CLASS_APP_ID,
  YOUR_HOME_LARGE_CLASS_APP_ID,
  YOUR_OVERSEAS_LARGE_CLASS_APP_ID,
  YOUR_HOME_BACKEND_URL,
  YOUR_OVERSEAS_BACKEND_URL,
  YOUR_SDK_TOKEN_URL
}
