# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'go_class' do
  # Comment the next line if you don't want to use dynamic frameworks use_frameworks!

  pod 'ZegoWhiteboardView/Express'
  pod 'ZegoDocsView/Basic_zh'
  
  
  pod 'YYWebImage'
  pod 'AFNetworking', '~> 4.0'
  pod 'YYModel'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'YYText'
  pod 'Masonry'
  pod 'libextobjc'
end

